diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  publish_rate: 50
  left_wheel_names: ["left_wheel_joint"]
  right_wheel_names: ["right_wheel_joint"]
  wheel_separation: 0.5
  wheel_radius: 0.1
  cmd_vel_timeout: 0.25
  use_stamped_vel: false
  base_frame_id: base_link
