global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 0.5
    static_map: true

    plugins:
      - {name: "static_layer", type: "nav2_costmap_2d::StaticLayer"}
      - {name: "obstacle_layer", type: "nav2_costmap_2d::ObstacleLayer"}

    static_layer:
      enabled: true
      map_topic: /map

    obstacle_layer:
      enabled: true
      observation_sources: ultrasonic_sensor
      ultrasonic_sensor:
        data_type: Range
        topic: /ultrasonic_sensor_1
        marking: true
        clearing: true
        obstacle_range: 2.0
        raytrace_range: 2.5
