local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 1.0
    static_map: false
    rolling_window: true

    plugins:
      - {name: "obstacle_layer", type: "nav2_costmap_2d::ObstacleLayer"}
      - {name: "inflation_layer", type: "nav2_costmap_2d::InflationLayer"}

    obstacle_layer:
      enabled: true
      observation_sources: ultrasonic_sensor
      ultrasonic_sensor:
        data_type: Range
        topic: /ultrasonic
        marking: true
        clearing: true
        obstacle_range: 2.0
        raytrace_range: 2.5

    inflation_layer:
      enabled: true
      inflation_radius: 0.5
      cost_scaling_factor: 10.0
