controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["LeftWheel_link_joint"]
    right_wheel_names: ["RightWheel_link_joint"]

    wheel_separation: 0.57
    wheels_per_side: 1
    wheel_radius: 0.05
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link #could be body?
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false #was true initially
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 0.1
    linear.x.min_velocity: -0.1
    linear.x.max_acceleration: 0.5

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 0.2
    angular.z.min_velocity: -0.2
    angular.z.max_acceleration: 0.5
